#!/bin/sh
case "$1" in
start) mkdir /var/lock/subsys 2>/dev/null
       touch /var/lock/subsys/listener
       rm /dev/shm 2>/dev/null
       mkdir /dev/shm 2>/dev/null
       mount -t tmpfs shmfs -o size=2048m /dev/shm 
       touch /dev/shm/.oracle-shm
       exit 0
       ;;
status)
    if [ -e /dev/shm/.oracle-shm ]; then
        echo "started" 
        exit 0
    else
        echo "not started"
        exit 3
    fi ;;      
*) echo error
   exit 1 ;;
esac 